In [33]:
# The code was removed by Watson Studio for sharing.

2021-10-11 15:38:23,551 - __PROJECT_LIB__ - ERROR - failed to initialize ibmos2spark integration
Traceback (most recent call last):
  File "/opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages/project_lib/storage/bcos.py", line 138, in _initialize_bcos2spark
    import ibmos2spark
ModuleNotFoundError: No module named 'ibmos2spark'


### Preparing the Dataset

#### Importing the libraries

In [1]:
import numpy as np
import pandas as pd

In [22]:
DSX_PROJECT_DIR  = "C://Users//100529706//Documents//My Activities//SolutionData//WML//model-mgmt-on-watson-studio-local-master//data//"

#### Importing the dataset

In [2]:
# The code was removed by Watson Studio for sharing.

In [3]:
dataset.head(2)

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1

In [4]:
X[0:2]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03]])

In [5]:
y[0:2]

array([1, 1])

### Feature Engineering

#### Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [7]:
X[0:2]

array([[ 1.51861254, -0.5622498 ,  0.23205254, -1.16959318,  1.91390522,
         0.80899739,  1.03481896, -0.65956311,  1.22488398,  0.25171685,
         0.36217728,  1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, -2.49084714,  0.01814502,
         0.56864766,  0.73362894, -0.82071924, -0.54472099, -0.29332133,
         0.40605066,  1.1134493 ,  0.96524152]])

#### Applying PCA

In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
X = pca.fit_transform(X)

In [9]:
X[0:2]

array([[ 3.31675081, -1.44346263],
       [ 2.20946492,  0.33339289]])

In [10]:
explained_variance = pca.explained_variance_ratio_
explained_variance*100

array([36.1988481 , 19.20749026])

### Exporting the results

In [34]:
features = pd.DataFrame(X)
#features.to_csv(os.environ['DSX_PROJECT_DIR']+'/datasets/features.csv')
#features.to_csv(DSX_PROJECT_DIR + 'features.csv')
pc.save_data("features.csv", features.to_csv(index=False))

#features.to_csv('features.csv')
features.head(2)

0         1
0  3.316751 -1.443463
1  2.209465  0.333393

In [36]:
target = pd.DataFrame(y)
#target.to_csv(os.environ['DSX_PROJECT_DIR']+'/datasets/target.csv')
#target.to_csv('target.csv')
pc.save_data("target.csv", target.to_csv(index=False))

target[0:2]

0
0  1
1  1